# Generated by Django 4.2.7 on 2023-11-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functionalities', '0002_alter_user_charger_type_alter_user_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='../static/images/default_image.jpg', upload_to='../static/images/'),
        ),
    ]
